import React, { createContext, useContext, useState, useEffect } from 'react';
import { AppLanguage, WorkspaceType } from '../types';

export interface TaxonomyMatrix {
  workspaceLabel: string;
  directoryName: string;
  memberTerm: string;
  fundsTerm: string;
  assetsTerm: string;
  inventoryTerm: string;
  memberNoun?: string;
  kartaNoun?: string;
  offeringNoun?: string;
}

const TAXONOMY_MAP: Record<AppLanguage, Record<WorkspaceType, TaxonomyMatrix>> = {
  en: {
    Mandir: {
      workspaceLabel: 'Mandir / Temple',
      directoryName: 'Devotee Directory',
      memberTerm: 'Bhaktas',
      fundsTerm: 'Chanda / Pranami',
      assetsTerm: 'Temple Assets',
      inventoryTerm: 'Bhandara & Store',
    },
    Goshala: {
      workspaceLabel: 'Goshala',
      directoryName: 'Gau Sevak Directory',
      memberTerm: 'Gau Sevaks',
      fundsTerm: 'Gau Seva Nidhi',
      assetsTerm: 'Gomata & Nandi Records',
      inventoryTerm: 'Fodder & Medicine Store',
    },
    Sangha: {
      workspaceLabel: 'Sangha / Youth Org',
      directoryName: 'Sangha Member Registry',
      memberTerm: 'Sadasya',
      fundsTerm: 'Sahayog Nidhi',
      assetsTerm: 'Sangha Assets',
      inventoryTerm: 'Logistics Store',
    },
    Ashram: {
      workspaceLabel: 'Ashram / Matha',
      directoryName: 'Sadhak Directory',
      memberTerm: 'Sadhaks',
      fundsTerm: 'Ashram Nidhi',
      assetsTerm: 'Ashram Estate',
      inventoryTerm: 'Kitchen & Medicine Store',
    },
    Gurukul: {
      workspaceLabel: 'Gurukul / Vidyapeeth',
      directoryName: 'Vidyarthi Directory',
      memberTerm: 'Vidyarthis',
      fundsTerm: 'Guru Dakshina',
      assetsTerm: 'Campus Assets',
      inventoryTerm: 'Library & Shastric Supplies',
    },
    Satsang: {
      workspaceLabel: 'Satsang Kendra',
      directoryName: 'Anuyayi Directory',
      memberTerm: 'Anuyayis',
      fundsTerm: 'Bhent / Pranami',
      assetsTerm: 'Kendra Assets',
      inventoryTerm: 'Store Management',
    },
    Yoga: {
      workspaceLabel: 'Yoga Kendra',
      directoryName: 'Practitioner Directory',
      memberTerm: 'Sadhaks',
      fundsTerm: 'Yoga Nidhi',
      assetsTerm: 'Wellness Equipment',
      inventoryTerm: 'Store & Props',
    },
    Trust: {
      workspaceLabel: 'Seva Trust',
      directoryName: 'Sevadar Directory',
      memberTerm: 'Sevadars',
      fundsTerm: 'Seva Nidhi',
      assetsTerm: 'Trust Assets',
      inventoryTerm: 'Relief & Medical Store',
    },
    Tirth: {
      workspaceLabel: 'Tirth / Dham',
      directoryName: 'Yatri Directory',
      memberTerm: 'Yatris',
      fundsTerm: 'Tirth Nidhi',
      assetsTerm: 'Dham Assets',
      inventoryTerm: 'Guest Houses & Supplies',
    },
    Samaj: {
      workspaceLabel: 'Samaj / Caste Sabha',
      directoryName: 'Family Directory',
      memberTerm: 'Jati Sadasya',
      fundsTerm: 'Samaj Sahayog',
      assetsTerm: 'Samaj Bhawan Assets',
      inventoryTerm: 'Event Supplies',
    },
    AkshayaPatra: {
      workspaceLabel: 'Annadanam & Kitchen Hub',
      directoryName: 'Mahaprasad Beneficiary Log',
      memberTerm: 'Annadata Patrons',
      fundsTerm: 'Annadanam Nidhi',
      assetsTerm: 'Kitchen & Vessel Assets',
      inventoryTerm: 'Ration & Grain Silos',
    },
    KashiKshetra: {
      workspaceLabel: 'Kashi Kshetra & Mukti Dham',
      directoryName: 'Pitru Moksha Roster',
      memberTerm: 'Tirtha Sadhaks',
      fundsTerm: 'Tarpan & Shradh Nidhi',
      assetsTerm: 'Ghat & Sanctum Assets',
      inventoryTerm: 'Samagri & Pinda Dravya',
    },
    DharmadaTrust: {
      workspaceLabel: 'Dharmada Seva Trust',
      directoryName: 'Trust Donor Registry',
      memberTerm: 'Trustee Patrons',
      fundsTerm: 'Dharmada Corpus',
      assetsTerm: 'Endowment Properties',
      inventoryTerm: 'Seva Logistics & Relief',
    },
    MahotsavSamiti: {
      workspaceLabel: 'Mahotsav & Utsav Samiti',
      directoryName: 'Festival Committee Roster',
      memberTerm: 'Utsav Karyakartas',
      fundsTerm: 'Mahotsav Chanda',
      assetsTerm: 'Pandal & Sound Assets',
      inventoryTerm: 'Decorations & Bhog Stores',
    },
    PurohitSabha: {
      workspaceLabel: 'Purohit & Vidwat Sabha',
      directoryName: 'Vedic Scholar Registry',
      memberTerm: 'Archakas & Acharyas',
      fundsTerm: 'Dakshina Pool',
      assetsTerm: 'Yajna Shala Assets',
      inventoryTerm: 'Vedic Samagri & Grantha',
    },
  },
  hi: {
    Mandir: {
      workspaceLabel: 'मंदिर / देवालय',
      directoryName: 'भक्त नामावली',
      memberTerm: 'भक्तगण',
      fundsTerm: 'चंदा / प्रणामी निधि',
      assetsTerm: 'मंदिर देव संपदा',
      inventoryTerm: 'भंडारा व सामग्री कक्ष',
    },
    Goshala: {
      workspaceLabel: 'गोशाला',
      directoryName: 'गोसेवक पंजिका',
      memberTerm: 'गोसेवक',
      fundsTerm: 'गोसेवा निधि',
      assetsTerm: 'गोमाता व नंदी अभिलेख',
      inventoryTerm: 'चारा एवं औषधि भंडार',
    },
    Sangha: {
      workspaceLabel: 'संघ / युवा संगठन',
      directoryName: 'संघ सदस्य पंजिका',
      memberTerm: 'स्वयंसेवक / सदस्य',
      fundsTerm: 'सहयोग निधि',
      assetsTerm: 'संघ संपदा',
      inventoryTerm: 'लॉजिस्टिक्स भंडार',
    },
    Ashram: {
      workspaceLabel: 'आश्रम / मठ',
      directoryName: 'साधक पंजिका',
      memberTerm: 'साधक',
      fundsTerm: 'आश्रम निधि',
      assetsTerm: 'आश्रम संपदा',
      inventoryTerm: 'रसोई व औषधि भंडार',
    },
    Gurukul: {
      workspaceLabel: 'गुरुकुल / विद्यापीठ',
      directoryName: 'विद्यार्थी पंजिका',
      memberTerm: 'विद्यार्थी / बटुक',
      fundsTerm: 'गुरु दक्षिणा',
      assetsTerm: 'परिसर संपदा',
      inventoryTerm: 'पुस्तकालय व शास्त्रीय सामग्री',
    },
    Satsang: {
      workspaceLabel: 'सत्संग केंद्र',
      directoryName: 'अनुयायी पंजिका',
      memberTerm: 'अनुयायी',
      fundsTerm: 'भेंट / प्रणामी',
      assetsTerm: 'केंद्र संपदा',
      inventoryTerm: 'सामग्री प्रबंधन',
    },
    Yoga: {
      workspaceLabel: 'योग केंद्र',
      directoryName: 'योगाभ्यासी पंजिका',
      memberTerm: 'साधक',
      fundsTerm: 'योग निधि',
      assetsTerm: 'स्वास्थ्य उपकरण',
      inventoryTerm: 'योग साधन भंडार',
    },
    Trust: {
      workspaceLabel: 'सेवा न्यास / ट्रस्ट',
      directoryName: 'सेवादार पंजिका',
      memberTerm: 'सेवादार',
      fundsTerm: 'सेवा निधि',
      assetsTerm: 'न्यास संपदा',
      inventoryTerm: 'राहत व चिकित्सा सामग्री',
    },
    Tirth: {
      workspaceLabel: 'तीर्थ / धाम',
      directoryName: 'यात्री पंजिका',
      memberTerm: 'तीर्थयात्री',
      fundsTerm: 'तीर्थ निधि',
      assetsTerm: 'धाम संपदा',
      inventoryTerm: 'अतिथि भवन व सामग्री',
    },
    Samaj: {
      workspaceLabel: 'समाज / जाति सभा',
      directoryName: 'परिवार पंजिका',
      memberTerm: 'ज्ञाति सदस्य',
      fundsTerm: 'समाज सहयोग',
      assetsTerm: 'समाज भवन संपदा',
      inventoryTerm: 'समारोह सामग्री',
    },
    AkshayaPatra: {
      workspaceLabel: 'अन्नदान व महाप्रसाद केंद्र',
      directoryName: 'अन्नदाता व लाभार्थी पंजिका',
      memberTerm: 'अन्नदाता',
      fundsTerm: 'अन्नदान निधि',
      assetsTerm: 'पाकशाला एवं पात्र संपदा',
      inventoryTerm: 'धान्य एवं रसद भंडार',
    },
    KashiKshetra: {
      workspaceLabel: 'काशी क्षेत्र व मुक्ति धाम',
      directoryName: 'पितृ मोक्ष पंजिका',
      memberTerm: 'तीर्थ साधक',
      fundsTerm: 'तर्पण एवं श्राद्ध निधि',
      assetsTerm: 'घाट एवं देवस्थान संपदा',
      inventoryTerm: 'पूजा सामग्री व पिण्ड द्रव्य',
    },
    DharmadaTrust: {
      workspaceLabel: 'धर्मदा सेवा न्यास',
      directoryName: 'दाता एवं न्यासी पंजिका',
      memberTerm: 'संरक्षक न्यासी',
      fundsTerm: 'धर्मदा कोष',
      assetsTerm: 'स्थायी परिसंपत्ति',
      inventoryTerm: 'राहत व वितरण सामग्री',
    },
    MahotsavSamiti: {
      workspaceLabel: 'महोत्सव व उत्सव समिति',
      directoryName: 'उत्सव समिति पंजिका',
      memberTerm: 'उत्सव कार्यकर्ता',
      fundsTerm: 'महोत्सव चंदा व सहयोग',
      assetsTerm: 'मंडप व विद्युत सज्जा संपदा',
      inventoryTerm: 'सज्जा व भोग भंडार',
    },
    PurohitSabha: {
      workspaceLabel: 'पुरोहित एवं विद्वत सभा',
      directoryName: 'वैदिक विद्वान पंजिका',
      memberTerm: 'अर्चक व आचार्य',
      fundsTerm: 'दक्षिणा कोष',
      assetsTerm: 'यज्ञशाला संपदा',
      inventoryTerm: 'वैदिक सामग्री व ग्रंथालय',
    },
  },
  bn: {
    Mandir: {
      workspaceLabel: 'মন্দির / দেবস্থান',
      directoryName: 'ভক্ত নির্দেশিকা',
      memberTerm: 'ভক্তবৃন্দ',
      fundsTerm: 'চাঁদা / প্রণামী তহবিল',
      assetsTerm: 'মন্দির দেবোত্তর সম্পত্তি',
      inventoryTerm: 'ভাণ্ডার ও সামগ্রী কক্ষ',
    },
    Goshala: {
      workspaceLabel: 'গোশালা',
      directoryName: 'গোসেবক তালিকা',
      memberTerm: 'গোসেবকবৃন্দ',
      fundsTerm: 'গোসেবা তহবিল',
      assetsTerm: 'গোমাতা ও নন্দী নথি',
      inventoryTerm: 'গোখাদ্য ও ঔষধাগার',
    },
    Sangha: {
      workspaceLabel: 'সঙ্ঘ / যুব সংগঠন',
      directoryName: 'সঙ্ঘ সদস্য রেজিস্ট্রি',
      memberTerm: 'সদস্যবৃন্দ',
      fundsTerm: 'সহযোগ তহবিল',
      assetsTerm: 'সঙ্ঘের সম্পদ',
      inventoryTerm: 'রসদ ভাণ্ডার',
    },
    Ashram: {
      workspaceLabel: 'আশ্রম / মঠ',
      directoryName: 'সাধক নির্দেশিকা',
      memberTerm: 'সাধকগণ',
      fundsTerm: 'আশ্রম তহবিল',
      assetsTerm: 'আশ্রম ভূসম্পত্তি',
      inventoryTerm: 'রান্নাঘর ও চিকিৎসালয়',
    },
    Gurukul: {
      workspaceLabel: 'গুরুকুল / বিদ্যাপীঠ',
      directoryName: 'শিক্ষার্থী নির্দেশিকা',
      memberTerm: 'শিক্ষার্থীবৃন্দ',
      fundsTerm: 'গুরু দক্ষিণা',
      assetsTerm: 'ক্যাম্পাস সম্পদ',
      inventoryTerm: 'গ্রন্থাগার ও শাস্ত্রীয় রসদ',
    },
    Satsang: {
      workspaceLabel: 'সৎসঙ্গ কেন্দ্র',
      directoryName: 'অনুযায়ী তালিকা',
      memberTerm: 'অনুযায়ীগণ',
      fundsTerm: 'ভেট / প্রণামী',
      assetsTerm: 'কেন্দ্র সম্পদ',
      inventoryTerm: 'ভাণ্ডার ব্যবস্থাপনা',
    },
    Yoga: {
      workspaceLabel: 'যোগ কেন্দ্র',
      directoryName: 'যোগাভ্যাসী তালিকা',
      memberTerm: 'সাধকবৃন্দ',
      fundsTerm: 'যোগ তহবিল',
      assetsTerm: 'সুস্থতা সরঞ্জাম',
      inventoryTerm: 'যোগ সামগ্রী ভাণ্ডার',
    },
    Trust: {
      workspaceLabel: 'সেবা ট্রাস্ট',
      directoryName: 'সেবাদার তালিকা',
      memberTerm: 'সেবাদারগণ',
      fundsTerm: 'সেবা তহবিল',
      assetsTerm: 'ট্রাস্ট সম্পদ',
      inventoryTerm: 'ত্রাণ ও চিকিৎসা ভাণ্ডার',
    },
    Tirth: {
      workspaceLabel: 'তীর্থ / ধাম',
      directoryName: 'যাত্রী নির্দেশিকা',
      memberTerm: 'তীর্থযাত্রীগণ',
      fundsTerm: 'তীর্থ তহবিল',
      assetsTerm: 'ধাম সম্পদ',
      inventoryTerm: 'অতিথি ভবন ও রসদ',
    },
    Samaj: {
      workspaceLabel: 'সমাজ / জ্ঞাতি সভা',
      directoryName: 'পরিবার নির্দেশিকা',
      memberTerm: 'জ্ঞাতি সদস্যবৃন্দ',
      fundsTerm: 'সমাজ সহযোগিতা',
      assetsTerm: 'সমাজ ভবন সম্পদ',
      inventoryTerm: 'অনুষ্ঠান সামগ্রী',
    },
    AkshayaPatra: {
      workspaceLabel: 'অন্নদান ও মহাপ্রসাদ কেন্দ্র',
      directoryName: 'অন্নদাতা ও গ্রাহক তালিকা',
      memberTerm: 'অন্নদাতাবৃন্দ',
      fundsTerm: 'অন্নদান তহবিল',
      assetsTerm: 'পাকশালা ও বাসনপত্র সম্পদ',
      inventoryTerm: 'চাল-ডাল ও রসদ ভাণ্ডার',
    },
    KashiKshetra: {
      workspaceLabel: 'কাশী ক্ষেত্র ও মুক্তিধাম',
      directoryName: 'পিতৃ মোক্ষ তালিকা',
      memberTerm: 'তীর্থ সাধকগণ',
      fundsTerm: 'তর্পণ ও শ্রাদ্ধ তহবিল',
      assetsTerm: 'ঘাট ও দেবালয় সম্পদ',
      inventoryTerm: 'পূজা সামগ্রী ও পিণ্ড দ্রব্য',
    },
    DharmadaTrust: {
      workspaceLabel: 'ধর্মদা সেবা ট্রাস্ট',
      directoryName: 'দাতা ও ট্রাস্টি রেজিস্ট্রি',
      memberTerm: 'পৃষ্ঠপোষক ট্রাস্টি',
      fundsTerm: 'ধর্মদা তহবিল',
      assetsTerm: 'স্থাবর সম্পত্তি',
      inventoryTerm: 'ত্রাণ ও বিতরণ সামগ্রী',
    },
    MahotsavSamiti: {
      workspaceLabel: 'মহোৎসব ও উৎসব সমিতি',
      directoryName: 'উৎসব কমিটি তালিকা',
      memberTerm: 'উৎসব কর্মী',
      fundsTerm: 'মহোৎসব চাঁদা ও অনুদান',
      assetsTerm: 'মন্ডপ ও আলোকসজ্জা সম্পদ',
      inventoryTerm: 'সজ্জা ও ভোগ ভাণ্ডার',
    },
    PurohitSabha: {
      workspaceLabel: 'পুরোহিত ও বিদ্বৎ সভা',
      directoryName: 'বৈদিক পণ্ডিত রেজিস্ট্রি',
      memberTerm: 'আচার্য ও অর্চকবৃন্দ',
      fundsTerm: 'দক্ষিণা পুল',
      assetsTerm: 'যজ্ঞশালা সম্পদ',
      inventoryTerm: 'বৈদিক সামগ্রী ও শাস্ত্রগ্রন্থ',
    },
  },
};

const UI_DICTIONARY: Record<AppLanguage, Record<string, string>> = {
  en: {
    dashboard: 'Command Center',
    searchPlaceholder: 'Search anything across 46 desks, members, transactions, gotras...',
    devotees: 'Devotees & Members',
    family: 'Household & Kul',
    vanshavali: 'Ancestral Lineage (Vanshavali)',
    guests: 'Visitor & Guest CRM',
    bulkImport: 'Bulk CSV Ingestion',
    treasury: 'Double-Entry Treasury',
    taxReceipts: 'Tax Certificates (80G/12A)',
    campaigns: 'Crowdfunding & Mandir Nirman',
    karmaLedger: 'Karma Merit Ledger',
    assets: 'Fixed Assets Ledger',
    inventory: 'Store & Consumables',
    poojaBooking: 'Rituals & Sankalp Hub',
    mandirPuja: 'Daily Aarti & Pujas',
    purohitDesk: 'Purohit Diary & Dakshina',
    purohitMarket: 'Global Scholar Marketplace',
    pitruShradh: 'Pitru Paksha & Shradh',
    panchang: 'Vedic Panjika & Muhurat',
    goshala: 'Goshala Sanctuary',
    annadanam: 'Annadanam & Prasad Seva',
    ashramKutir: 'Ashram & Kutir Stays',
    dharamshala: 'Dharamshala Yatri Bhavan',
    gurukul: 'Gurukul Residential',
    gurukulAcademy: 'Shastric Academy & Grading',
    vidyalaya: 'Weekend Heritage School',
    satsang: 'Satsang & Discourse',
    sanghaDrills: 'Sangha & Shakha Mobilization',
    sevaTrust: 'Humanitarian Seva Trust',
    granthLibrary: 'Sacred Granth Library',
    matrimony: 'Vivah Bandhan (Matchmaking)',
    utsavPanjika: 'Festival Calendar & Passes',
    panchayatPolls: 'Panchayat Voting & Quorum',
    sandeshBroadcast: 'Sandesh WhatsApp/SMS',
    socialWall: 'Temple Wall & Darshan',
    shlokaFeed: 'Shloka Wisdom Feed',
    dharmaMarketing: 'Dharma Marketing AI',
    trusteeGovernance: 'Trustee Governance',
    legalVault: 'Encrypted Legal Vault',
    sevadarRoster: 'Sevadar Shift Roster',
    masterSettings: 'Organization Settings',
    spiritualSettings: 'Sampradaya & Kuladevata',
    platformBroadcast: 'Super Admin Broadcasts',
    mySpace: 'My Space & ID Pass',
    logout: 'Switch Account / Logout',
    totalMembers: 'Total Enrolled',
    totalTreasury: 'Treasury Balance',
    activeCampaigns: 'Active Seva Campaigns',
    todaysTithi: "Today's Tithi & Muhurat",
    viewAll: 'View All',
    actions: 'Actions',
    downloadPdf: 'Download PDF',
    exportCsv: 'Export CSV',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirm: 'Confirm',
    addRecord: 'Add Record',
    quickPay: 'Log Chanda / Dakshina',
    printIdCard: 'Smart Devotee Card',
    liveTelemetry: 'GA4 Telemetry Monitor',
    footerText: 'Made with ❤️ by TrackIQ Academy • Universal Community Management',
  },
  hi: {
    dashboard: 'कमांड सेंटर',
    searchPlaceholder: '४६ डेस्क, सदस्य, लेन-देन, गोत्र आदि खोजें...',
    devotees: 'भक्त एवं सदस्य पंजिका',
    family: 'परिवार एवं कुल पंजिका',
    vanshavali: 'वंशावली व कुलवृक्ष',
    guests: 'अतिथि व आगंतुक पंजिका',
    bulkImport: 'बल्क सीएसवी आयात',
    treasury: 'द्वि-प्रविष्टि राजकोष / बहीखाता',
    taxReceipts: 'दान प्रमाण पत्र (80G/12A)',
    campaigns: 'मंदिर निर्माण व जनसहयोग',
    karmaLedger: 'कर्म पुण्य बहीखाता',
    assets: 'अचल देव संपदा पंजिका',
    inventory: 'भंडार व सामग्री भंडार',
    poojaBooking: 'पूजा संकल्प व अनुष्ठान',
    mandirPuja: 'दैनिक आरती व सेवा',
    purohitDesk: 'पुरोहित डायरी व दक्षिणा',
    purohitMarket: 'वैदिक विद्वान मंच',
    pitruShradh: 'पितृ पक्ष व श्राद्ध स्मरण',
    panchang: 'वैदिक पंचांग व शुभ मुहूर्त',
    goshala: 'गोशाला प्रबंधन',
    annadanam: 'अन्नदानम् व महाप्रसाद',
    ashramKutir: 'आश्रम कुटीर व साधना',
    dharamshala: 'धर्मशाला यात्री भवन',
    gurukul: 'गुरुकुल आवासीय प्रणाली',
    gurukulAcademy: 'शास्त्र अकादमी व मूल्यांकन',
    vidyalaya: 'साप्ताहिक संस्कार विद्यालय',
    satsang: 'सत्संग व हरि कथा',
    sanghaDrills: 'संघ शाखा व स्वयंसेवक संघटन',
    sevaTrust: 'मानव सेवा न्यास',
    granthLibrary: 'पवित्र ग्रन्थ पुस्तकालय',
    matrimony: 'विवाह बंधन (धार्मिक संबंध)',
    utsavPanjika: 'उत्सव पंजिका व प्रवेश पास',
    panchayatPolls: 'पंचायत मतदान व कोरम',
    sandeshBroadcast: 'संदेश प्रसारण (व्हाट्सएप/एसएमएस)',
    socialWall: 'दैनिक दर्शन व सूचना पट',
    shlokaFeed: 'श्लोक अमृत प्रवाह',
    dharmaMarketing: 'धर्म प्रचार एआई',
    trusteeGovernance: 'न्यास शासन व प्रस्ताव',
    legalVault: 'विधिक प्रलेख तिजोरी',
    sevadarRoster: 'सेवादार समय सारणी',
    masterSettings: 'संस्थान विन्यास',
    spiritualSettings: 'सम्प्रदाय व कुलदेवता',
    platformBroadcast: 'प्लेटफॉर्म घोषणाएं',
    mySpace: 'मेरी पंजिका व स्मार्ट पास',
    logout: 'खाता बदलें / लॉग आउट',
    totalMembers: 'कुल नामांकित',
    totalTreasury: 'राजकोष शेष',
    activeCampaigns: 'सक्रिय सेवा अभियान',
    todaysTithi: 'आज की तिथि व शुभ मुहूर्त',
    viewAll: 'सभी देखें',
    actions: 'कार्यवाही',
    downloadPdf: 'पीडीएफ डाउनलोड',
    exportCsv: 'सीएसवी निर्यात',
    saveChanges: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    addRecord: 'नई प्रविष्टि',
    quickPay: 'चंदा / दक्षिणा दर्ज करें',
    printIdCard: 'स्मार्ट भक्त कार्ड',
    liveTelemetry: 'जीए४ लाइव टेलीमेट्री मॉनिटर',
    footerText: 'Made with ❤️ by TrackIQ Academy • Universal Community Management',
  },
  bn: {
    dashboard: 'কমান্ড সেন্টার',
    searchPlaceholder: '৪৬টি ডেস্ক, সদস্য, লেনদেন, গোত্র অনুসন্ধান করুন...',
    devotees: 'ভক্ত ও সদস্য তালিকা',
    family: 'পরিবার ও কুল নথি',
    vanshavali: 'বংশাবলি ও পূর্বপুরুষ বৃক্ষ',
    guests: 'অতিথি ও দর্শনার্থী রেজিস্টার',
    bulkImport: 'বাল্ক সিএসভি আপলোড',
    treasury: 'দ্বি-ভুক্তি রাজকোষ খতিয়ান',
    taxReceipts: 'কর ছাড় সনদপত্র (80G/12A)',
    campaigns: 'মন্দির নির্মাণ ও ক্রাউডফান্ডিং',
    karmaLedger: 'কর্ম পুণ্য খতিয়ান',
    assets: 'স্থাবর দেবোত্তর সম্পত্তি',
    inventory: 'ভাণ্ডার ও রসদ সামগ্রী',
    poojaBooking: 'পূজা সংকল্প ও উপচার',
    mandirPuja: 'দৈনিক আরতি ও পুষ্পাঞ্জলি',
    purohitDesk: 'পুরোহিত ডায়েরি ও দক্ষিণা',
    purohitMarket: 'বৈদিক পন্ডিত মার্কেটপ্লেস',
    pitruShradh: 'পিতৃপক্ষ ও বাৎসরিক শ্রাদ্ধ',
    panchang: 'বৈদিক পঞ্জিকা ও শুভ মুহূর্ত',
    goshala: 'গোশালা অভয়ারণ্য',
    annadanam: 'অন্নদান ও মহাপ্রসাদ সেবা',
    ashramKutir: 'আশ্রম কুটির ও সাধনা',
    dharamshala: 'ধর্মশালা যাত্রী ভবন',
    gurukul: 'গুরুকুল আবাসিক ব্যবস্থা',
    gurukulAcademy: 'শাস্ত্রীয় অ্যাকাডেমি ও মূল্যায়ন',
    vidyalaya: 'সাপ্তাহিক ঐতিহ্য বিদ্যালয়',
    satsang: 'সৎসঙ্গ ও হরিকথা',
    sanghaDrills: 'সঙ্ঘ শাখা ও স্বয়ংসেবক পরিচালনা',
    sevaTrust: 'মানবসেবা ট্রাস্ট',
    granthLibrary: 'পবিত্র গ্রন্থ পাঠাগার',
    matrimony: 'বিবাহ বন্ধন (ধর্মীয় সম্বন্ধ)',
    utsavPanjika: 'উৎসব পঞ্জিকা ও প্রবেশ পাস',
    panchayatPolls: 'পঞ্চায়েত ভোটদান ও কোরাম',
    sandeshBroadcast: 'বার্তা প্রচার (হোয়াটসঅ্যাপ/এসএমএস)',
    socialWall: 'মন্দির প্রাচীর ও দর্শন',
    shlokaFeed: 'শ্লোক অমৃত জ্ঞান',
    dharmaMarketing: 'ধর্ম প্রচার এআই',
    trusteeGovernance: 'ট্রাস্টি বোর্ড ও প্রস্তাবনা',
    legalVault: 'সুরক্ষিত আইনি সিন্দুক',
    sevadarRoster: 'সেবাদার পালা তালিকা',
    masterSettings: 'সংগঠন সেটিংস',
    spiritualSettings: 'সম্প্রদায় ও কুলদেবতা',
    platformBroadcast: 'সুপার অ্যাডমিন বার্তা',
    mySpace: 'আমার স্পেস ও স্মার্ট পাস',
    logout: 'অ্যাকাউন্ট বদলান / লগ আউট',
    totalMembers: 'মোট নথিভুক্ত',
    totalTreasury: 'রাজকোষ স্থিতি',
    activeCampaigns: 'চলমান সেবা অভিযান',
    todaysTithi: 'আজকের তিথি ও শুভ মুহূর্ত',
    viewAll: 'সব দেখুন',
    actions: 'পদক্ষেপ',
    downloadPdf: 'পিডিএফ ডাউনলোড',
    exportCsv: 'সিএসভি রপ্তানি',
    saveChanges: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    addRecord: 'নতুন এন্ট্রি',
    quickPay: 'প্রণামী / চাঁদা জমা দিন',
    printIdCard: 'স্মার্ট ভক্ত কার্ড',
    liveTelemetry: 'জিএ৪ লাইভ টেলিমেট্রি',
    footerText: 'Made with ❤️ by TrackIQ Academy • Universal Community Management',
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
  getTaxonomy: (workspaceType: WorkspaceType) => TaxonomyMatrix;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    const saved = localStorage.getItem('sanatani_app_lang');
    return (saved as AppLanguage) || 'en';
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('sanatani_app_lang', lang);
  };

  const t = (key: string): string => {
    const currentDict = UI_DICTIONARY[language] || UI_DICTIONARY.en;
    return currentDict[key] || UI_DICTIONARY.en[key] || key;
  };

  const getTaxonomy = (workspaceType: WorkspaceType): TaxonomyMatrix => {
    const matrix = TAXONOMY_MAP[language]?.[workspaceType] || TAXONOMY_MAP.en[workspaceType] || TAXONOMY_MAP.en.Mandir;
    return {
      ...matrix,
      memberNoun: matrix.memberTerm,
      kartaNoun: matrix.memberTerm,
      offeringNoun: matrix.fundsTerm,
    };
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getTaxonomy }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
